env:
  browser: true
  es2021: true
  jest: true
extends:
  - standard
overrides:
  - files: ['*.ts', '*.tsx']
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  semi: [2, 'always']
